name: Deploy apollo sevice on AWS
on:
  workflow_call:
    inputs:
      APOLLO_GRAPH_NAME:
        required: true
        type: string
      APOLLO_GRAPH_VARIANT:
        required: true
        type: string
      APOLLO_SCHEMA_REPORTING:
        required: true
        type: string
      MONGODB_DB_NAME:
        required: true
        type: string
      
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      APOLLO_KEY:
        required: true
      MONGODB_URL:
        required: true

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install NPM dependencies
        run: npm install

      - name: Generate typings from graphql schemas
        run: node_modules/.bin/graphql-codegen

      - name: Deploy
        run: APOLLO_GRAPH_NAME=${{ inputs.APOLLO_GRAPH_NAME }} APOLLO_KEY=${{ secrets.APOLLO_KEY }} APOLLO_GRAPH_VARIANT=${{ inputs.APOLLO_GRAPH_VARIANT }} APOLLO_SCHEMA_REPORTING=${{ inputs.APOLLO_SCHEMA_REPORTING }} MONGODB_DB_NAME=${{ inputs.MONGODB_DB_NAME }} MONGODB_URL=${{ secrets.MONGODB_URL }} sls deploy --verbose
